[[OpenSSH]]
arch = "aarch64"
git-tree-sha1 = "f34e4ddcad215f3d1a3d21e128d07d18df92e7fc"
os = "macos"

    [[OpenSSH.download]]
    sha256 = "229f1dcfd8b183a7159763660522766d7f6a699020d5347bfc9f8f8d78451119"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v9.2.0+0/OpenSSH.v9.2.0.aarch64-apple-darwin.tar.gz"
[[OpenSSH]]
arch = "aarch64"
git-tree-sha1 = "97def8eb99ab06db0b0ab6799c6c285a76407707"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "c7f618374c43a46626775fa7f31f311f708f8176e9fa05a3788e17545be5b643"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v9.2.0+0/OpenSSH.v9.2.0.aarch64-linux-gnu.tar.gz"
[[OpenSSH]]
arch = "aarch64"
git-tree-sha1 = "6c0d4e23d0bf8c366aad987fe6f91bea6b883189"
libc = "musl"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "03eec7c1f539979e9a32e2498cc891bfcb853c1f50c6790a1ccb018b1f86733c"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v9.2.0+0/OpenSSH.v9.2.0.aarch64-linux-musl.tar.gz"
[[OpenSSH]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "628ea3979af237c9745b8424e654a29b06733f7a"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "36d15e5dc124220e2c27ae31782385cf6dcb487503079323f166bfb119377df3"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v9.2.0+0/OpenSSH.v9.2.0.armv6l-linux-gnueabihf.tar.gz"
[[OpenSSH]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f7ccbddd76b0a2c7ee49f19f2f9fb691d37c0a11"
libc = "musl"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "0dea800be47c16b1d98e1e6fd3022f013cb377254eb9e44b78d2c0547e8ea438"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v9.2.0+0/OpenSSH.v9.2.0.armv6l-linux-musleabihf.tar.gz"
[[OpenSSH]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "84439f79b7cd976b97f87ed081cf9d6f46dcb00d"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "1536a00eb8353bbdcc8bb4425de09ca4d145bc207cef63d805b8c3fe39527137"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v9.2.0+0/OpenSSH.v9.2.0.armv7l-linux-gnueabihf.tar.gz"
[[OpenSSH]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6a64b924e41740931d8d5b85dabb87d53fb25aa2"
libc = "musl"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "eb924450bfbb216f9a5f93568eb425cf9306300802345f12c1b9ff82437c8642"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v9.2.0+0/OpenSSH.v9.2.0.armv7l-linux-musleabihf.tar.gz"
[[OpenSSH]]
arch = "i686"
git-tree-sha1 = "fdb3be62ae60d1ecb66655aa769c423674c53e53"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "fa42f19bd67e5cf2541d20766db3f81a2047c063bf3256c5e7543a0182c500a8"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v9.2.0+0/OpenSSH.v9.2.0.i686-linux-gnu.tar.gz"
[[OpenSSH]]
arch = "i686"
git-tree-sha1 = "5c65bc7f190746d16c5722810d6a0dbfc3e08854"
libc = "musl"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "d58f55ca11a301ee89258e75d341eb809cd8d3f76b849757f359e99675fca581"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v9.2.0+0/OpenSSH.v9.2.0.i686-linux-musl.tar.gz"
[[OpenSSH]]
arch = "i686"
git-tree-sha1 = "cf96e8622b072e040fda081fd2670e64eb385d25"
os = "windows"

    [[OpenSSH.download]]
    sha256 = "79709bba2f7bbeccf4efb1f94dfb67aa51d48a5a088c81b1cca04c80e74d1032"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v9.2.0+0/OpenSSH.v9.2.0.i686-w64-mingw32.tar.gz"
[[OpenSSH]]
arch = "powerpc64le"
git-tree-sha1 = "290bac9a17ea6e9aedf2485e43e6b54e382c7d99"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "6ef0f93fd46b48e26553815c8520f0668884dac0ea29c138efe8507bf94e559a"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v9.2.0+0/OpenSSH.v9.2.0.powerpc64le-linux-gnu.tar.gz"
[[OpenSSH]]
arch = "x86_64"
git-tree-sha1 = "99502e6f1cb020a1bb7b07fbdc62dd563bac3cdf"
os = "macos"

    [[OpenSSH.download]]
    sha256 = "457f16133958384cf542caf0d7fa18b09dd9d9bf289a48557c4d9247f4f98efa"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v9.2.0+0/OpenSSH.v9.2.0.x86_64-apple-darwin.tar.gz"
[[OpenSSH]]
arch = "x86_64"
git-tree-sha1 = "02dde97e60ee34cef61ecca47fb87cd6e05e6f86"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "93351dd1c260ea1d1011ae155076afc12caeb914367511889c1661164869dda9"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v9.2.0+0/OpenSSH.v9.2.0.x86_64-linux-gnu.tar.gz"
[[OpenSSH]]
arch = "x86_64"
git-tree-sha1 = "45145dc843a788155fac0613bfb3521db45a820e"
libc = "musl"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "6656296223883c1bc10b235bd1c684a336baef63407b98b744943a96eede079e"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v9.2.0+0/OpenSSH.v9.2.0.x86_64-linux-musl.tar.gz"
[[OpenSSH]]
arch = "x86_64"
git-tree-sha1 = "5ba27429e3addee957c74700a49d2ae7e81dd443"
os = "freebsd"

    [[OpenSSH.download]]
    sha256 = "843e41326fd1be62859551357c725bacd427892becb917e7f4ad88fb81c221f0"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v9.2.0+0/OpenSSH.v9.2.0.x86_64-unknown-freebsd.tar.gz"
[[OpenSSH]]
arch = "x86_64"
git-tree-sha1 = "65bbfc0b54f499e879f038a095acec450dbff365"
os = "windows"

    [[OpenSSH.download]]
    sha256 = "efc40f35176b3b212a356ec2f745ba6b466b4cd89377b01c445948ba53ed993a"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v9.2.0+0/OpenSSH.v9.2.0.x86_64-w64-mingw32.tar.gz"
