[[OpenSSH]]
arch = "aarch64"
git-tree-sha1 = "8ef2693a1c4995eafddf29c1211b3b94a9034fac"
os = "macos"

    [[OpenSSH.download]]
    sha256 = "329e584ad0e364fe06e16aba2012da8ceceab04658828954a7c418b3ba020a93"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v8.9.0+1/OpenSSH.v8.9.0.aarch64-apple-darwin.tar.gz"
[[OpenSSH]]
arch = "aarch64"
git-tree-sha1 = "24be4f4cf5f3ded758b30bd0cbb1535d94641052"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "97fed82286102a1bb3977c4e870f7e5828adc89d916c7b682e067a9b87179454"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v8.9.0+1/OpenSSH.v8.9.0.aarch64-linux-gnu.tar.gz"
[[OpenSSH]]
arch = "aarch64"
git-tree-sha1 = "be30323b737573de670ce311af48e13e826e8e26"
libc = "musl"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "b05b3fcee0e11bb64445c620ba9c5fffdda0bed99977084fb06a82bb8c06dd1d"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v8.9.0+1/OpenSSH.v8.9.0.aarch64-linux-musl.tar.gz"
[[OpenSSH]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "324fc554d262bb17890b60bdef47ad47e1c5fd96"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "9dd5007892f4fbb7b2995d72872070a3ad4f2711aecbf3eb0719f09e0d5f57f6"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v8.9.0+1/OpenSSH.v8.9.0.armv6l-linux-gnueabihf.tar.gz"
[[OpenSSH]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "fdc38b9a74529d4576a9b7d113e962d7cccfe170"
libc = "musl"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "bf71afbb754d488c8320ac9fe65ebde0a7fb9952dd4d71f3b69810a3eb064746"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v8.9.0+1/OpenSSH.v8.9.0.armv6l-linux-musleabihf.tar.gz"
[[OpenSSH]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f88e160349f439157a6534a8dd53d8de510956e7"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "bc7cbf0b02c3abcfd344fa06a7440cc8c427182034aba4ddcc89524fb0329f50"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v8.9.0+1/OpenSSH.v8.9.0.armv7l-linux-gnueabihf.tar.gz"
[[OpenSSH]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f5a6d61d66705de009dba2a4a1669618d6c87af5"
libc = "musl"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "54045f08c663701ecd10b4bc2fa5fc55146131e1ba3b3bf3f262c35108dabb40"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v8.9.0+1/OpenSSH.v8.9.0.armv7l-linux-musleabihf.tar.gz"
[[OpenSSH]]
arch = "i686"
git-tree-sha1 = "2b9c8c1ed9dbd4706c7a3afc709e9d9829f47a25"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "9d6bcfddebcb784a742be3dad867365a1953c28ea712cf8ba10373e6791539ad"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v8.9.0+1/OpenSSH.v8.9.0.i686-linux-gnu.tar.gz"
[[OpenSSH]]
arch = "i686"
git-tree-sha1 = "c8db8aaa4863a61b23dac20f5b45fc1077652503"
libc = "musl"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "3e3ca476ab1ae2b6b6f64835345937822a747dbbcd275ef5539530cf0d0ec2ec"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v8.9.0+1/OpenSSH.v8.9.0.i686-linux-musl.tar.gz"
[[OpenSSH]]
arch = "i686"
git-tree-sha1 = "1fad447175d190ff096e4d4c0564dd87d3fbaeb6"
os = "windows"

    [[OpenSSH.download]]
    sha256 = "8d33a49a91150f446c8d202c18fb9944d8d68b9d1a9c8b615a7d5300d82768a8"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v8.9.0+1/OpenSSH.v8.9.0.i686-w64-mingw32.tar.gz"
[[OpenSSH]]
arch = "powerpc64le"
git-tree-sha1 = "4c2145bfc1375048b1cc230b2eac3a798a134aed"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "0165d2b7b9f93b395e8f0db2c97f54913a0284a24348667edb5aac4a2e13954f"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v8.9.0+1/OpenSSH.v8.9.0.powerpc64le-linux-gnu.tar.gz"
[[OpenSSH]]
arch = "x86_64"
git-tree-sha1 = "9c73a8206cd5c1d60efbce1094d4c4ecfcf62f44"
os = "macos"

    [[OpenSSH.download]]
    sha256 = "3c7ed0ee91e61c7bdff79f739e02db1ca65a408c02899d21739e2e0c71167136"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v8.9.0+1/OpenSSH.v8.9.0.x86_64-apple-darwin.tar.gz"
[[OpenSSH]]
arch = "x86_64"
git-tree-sha1 = "cf570328554ecb898e625367a9c9fb2c01f55267"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "43286315e2e973d61e9da94f731e0d73be6cd195e4f58f282e0b2410e8eaaec4"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v8.9.0+1/OpenSSH.v8.9.0.x86_64-linux-gnu.tar.gz"
[[OpenSSH]]
arch = "x86_64"
git-tree-sha1 = "330e12d60279e490b38d90fb46d395c73270d540"
libc = "musl"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "885ebf62bbb9e607724bd1848f463c01e8ed31e37ca7451c6332606b9aab4473"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v8.9.0+1/OpenSSH.v8.9.0.x86_64-linux-musl.tar.gz"
[[OpenSSH]]
arch = "x86_64"
git-tree-sha1 = "8d18c6f70e358d2938670191f63719c9b92f53a2"
os = "freebsd"

    [[OpenSSH.download]]
    sha256 = "84fa9f70b4fddd714f89cea68f48c011014a9c3ace81161d7957b70a49884104"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v8.9.0+1/OpenSSH.v8.9.0.x86_64-unknown-freebsd.tar.gz"
[[OpenSSH]]
arch = "x86_64"
git-tree-sha1 = "29b66f847af6c9c6324db3acc63c159b47813c85"
os = "windows"

    [[OpenSSH.download]]
    sha256 = "ffbbf1565d067ea3e2f212ed72679ff4b3f05e5473911f98eac9b5f0d0990abd"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v8.9.0+1/OpenSSH.v8.9.0.x86_64-w64-mingw32.tar.gz"
