[[OpenSSH]]
arch = "aarch64"
git-tree-sha1 = "b123c3a330321f2c569d8c11e66a245fd9e5bfba"
os = "macos"

    [[OpenSSH.download]]
    sha256 = "0a4fed768a4126875ccf4ae8b6dccf3d0b08ddd7dc9947d09395a4804bde4a41"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.0.1+0/OpenSSH.v10.0.1.aarch64-apple-darwin.tar.gz"
[[OpenSSH]]
arch = "aarch64"
git-tree-sha1 = "476d0cb4f554c024f4081b6a40be7448e9e209e9"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "1bf4d28ba78accb86d52f086938378ddb6278e9901dae97e21be8380bf5da96e"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.0.1+0/OpenSSH.v10.0.1.aarch64-linux-gnu.tar.gz"
[[OpenSSH]]
arch = "aarch64"
git-tree-sha1 = "64cd2d0b556e981dcbb4cabd0a3dc328c8cbe93f"
libc = "musl"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "a59a5900e6e0d48ab28fc9a1c653281eb1e4b6ae3a1af7c9b68a2358254a33af"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.0.1+0/OpenSSH.v10.0.1.aarch64-linux-musl.tar.gz"
[[OpenSSH]]
arch = "aarch64"
git-tree-sha1 = "02ba5aef6aeaf0b85fabd43733808ac136069cc4"
os = "freebsd"

    [[OpenSSH.download]]
    sha256 = "2a0e2e71fe88de1505f778a4a7e5af665a4ed84a1fcd1a5f78c5e1bf4ff6c738"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.0.1+0/OpenSSH.v10.0.1.aarch64-unknown-freebsd.tar.gz"
[[OpenSSH]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0a0a3a10655475e4c1f08082ee73fe1402d8d2ff"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "482a54054c00a24923d9a0d16c5b39a9548cf96d0a4c4042a7327a21d183add1"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.0.1+0/OpenSSH.v10.0.1.armv6l-linux-gnueabihf.tar.gz"
[[OpenSSH]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b5815db979d2515dc20e6f2c4acf43ca8d7a5b9f"
libc = "musl"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "f95d37d4465a5b049108e4beb8529816ae2806f94490033962108b8b1fa31e30"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.0.1+0/OpenSSH.v10.0.1.armv6l-linux-musleabihf.tar.gz"
[[OpenSSH]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "344e3a6688682f1d4a3e4293ec522d52cfa2ce11"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "743c32b703749c7139bfadfdc8db2b05b1889e935f7256d1164a3b5452dc1dda"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.0.1+0/OpenSSH.v10.0.1.armv7l-linux-gnueabihf.tar.gz"
[[OpenSSH]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c57e3dec1c6d6c58b2adbefb34ddbb925cbf55b5"
libc = "musl"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "d21c1f345b4674f818a1d78581a5a706874e54e603b20c9709c5cd31e9c01965"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.0.1+0/OpenSSH.v10.0.1.armv7l-linux-musleabihf.tar.gz"
[[OpenSSH]]
arch = "i686"
git-tree-sha1 = "22d5dc3dea07966104581750c72dcaa3294b3655"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "f56af83e181d6360e784478b622708c262bd6be378182e5ffdcd433422c6f742"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.0.1+0/OpenSSH.v10.0.1.i686-linux-gnu.tar.gz"
[[OpenSSH]]
arch = "i686"
git-tree-sha1 = "4ad5a4e98068b9e359f256effe94fc75e9c7e84d"
libc = "musl"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "5b0a06eac20d42a9dd755d60568aafac2843089761075eb049be063a8546d1f4"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.0.1+0/OpenSSH.v10.0.1.i686-linux-musl.tar.gz"
[[OpenSSH]]
arch = "i686"
git-tree-sha1 = "0279aef37eecab0756e7b3609dd09b7e1ec253b4"
os = "windows"

    [[OpenSSH.download]]
    sha256 = "d6534f16320caef56134fe81df6794c588084cb6962c3898f044e06d571bcf9c"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.0.1+0/OpenSSH.v10.0.1.i686-w64-mingw32.tar.gz"
[[OpenSSH]]
arch = "powerpc64le"
git-tree-sha1 = "76eff11ceeee924a5dc9ab86c77a90d033a9440c"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "7e789098a578cbd5fd5874c32119252dd25e6b3191769bc1fa0cb7f016ece274"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.0.1+0/OpenSSH.v10.0.1.powerpc64le-linux-gnu.tar.gz"
[[OpenSSH]]
arch = "riscv64"
git-tree-sha1 = "81d3d6780a3612e41ef28d6ef7fd20a65c2c45b3"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "a5b5badbcb52447f70b8be9ccc804653bd79feb2cead5d540115dde8df6169e8"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.0.1+0/OpenSSH.v10.0.1.riscv64-linux-gnu.tar.gz"
[[OpenSSH]]
arch = "x86_64"
git-tree-sha1 = "f0d9641c1527ae7c21446363d9c8d5a103273f4b"
os = "macos"

    [[OpenSSH.download]]
    sha256 = "10e51605ee108861deee126da7543868bdd0af548896a08aaccd69133b7ce1b8"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.0.1+0/OpenSSH.v10.0.1.x86_64-apple-darwin.tar.gz"
[[OpenSSH]]
arch = "x86_64"
git-tree-sha1 = "7b46720b034a5501393d9cbb503824d984b6c3d0"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "077d27aa3420d3031f38bef3666bacf9a29ea10afed693a5eeea3b404a42dd58"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.0.1+0/OpenSSH.v10.0.1.x86_64-linux-gnu.tar.gz"
[[OpenSSH]]
arch = "x86_64"
git-tree-sha1 = "e883cd80bad891cf39ce7aac3db0cfaa445bc960"
libc = "musl"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "9a754c71fdb231fea869ad3f13dc30dd4884a891df5fea9da62cd9c60265960f"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.0.1+0/OpenSSH.v10.0.1.x86_64-linux-musl.tar.gz"
[[OpenSSH]]
arch = "x86_64"
git-tree-sha1 = "6c112ce182d827e0837ad98223fd9df7e94ad0a7"
os = "freebsd"

    [[OpenSSH.download]]
    sha256 = "0dd3b8ee2b1b22d2af0304583fa0b095189f168523e25448afde26230bee89c2"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.0.1+0/OpenSSH.v10.0.1.x86_64-unknown-freebsd.tar.gz"
[[OpenSSH]]
arch = "x86_64"
git-tree-sha1 = "8a380ed334dece6e4696fa6c829049695e73a3b4"
os = "windows"

    [[OpenSSH.download]]
    sha256 = "8de6d3360c69955b45d8083b6c6e327e14606836600532073e7bd6af2fbe0975"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.0.1+0/OpenSSH.v10.0.1.x86_64-w64-mingw32.tar.gz"
