[[OpenSSH]]
arch = "aarch64"
git-tree-sha1 = "07febf4fd2216d435ddc7d8975f9f8e9358752ce"
os = "macos"

    [[OpenSSH.download]]
    sha256 = "b46245e82bf95c4b848c3e077898ce172d3b2b1048d8fcccc3cccb994fc0a30e"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v9.9.2+0/OpenSSH.v9.9.2.aarch64-apple-darwin.tar.gz"
[[OpenSSH]]
arch = "aarch64"
git-tree-sha1 = "3640b0b3a73f4fe0d8c2afd8ccb93dfcd2db7028"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "1b20f2e63ff5141fef4f5ceeacd7f6f8c31dd694dda00648ff45e3a403c09689"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v9.9.2+0/OpenSSH.v9.9.2.aarch64-linux-gnu.tar.gz"
[[OpenSSH]]
arch = "aarch64"
git-tree-sha1 = "a65f0faf054229a3b5fc2456824a136bcb08e075"
libc = "musl"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "628bc3810b76bd9defd6f78fdc195584993358e699d090ea7f90a3c8d31e0218"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v9.9.2+0/OpenSSH.v9.9.2.aarch64-linux-musl.tar.gz"
[[OpenSSH]]
arch = "aarch64"
git-tree-sha1 = "222cd6c0dacbbaeb30974739b543878cae27e7ca"
os = "freebsd"

    [[OpenSSH.download]]
    sha256 = "db779f3b0cad8bdbff6d5445d9eb7f58a6d303bbdc967359049956a68b74f3f8"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v9.9.2+0/OpenSSH.v9.9.2.aarch64-unknown-freebsd.tar.gz"
[[OpenSSH]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "59a1aba504580c75654ce11abd23f2a74a8c3970"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "f698ff5cd4765874a4d5770cb16ae1e76daf74179809ebeee8515937c582ee70"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v9.9.2+0/OpenSSH.v9.9.2.armv6l-linux-gnueabihf.tar.gz"
[[OpenSSH]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5076de06a5e1e522f161befd46c8b56de8e8aaa1"
libc = "musl"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "fe6a7c4c69167c86bf10fab06099ef1082eec43ddc1c391feafcce0bd84189f3"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v9.9.2+0/OpenSSH.v9.9.2.armv6l-linux-musleabihf.tar.gz"
[[OpenSSH]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e05b6dd86f021e86138ae3026da131fd1526af56"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "1fefec6360f0404e0d7bdf2ec23a908c99895e92cb0e37ba271bb4b047a2a4ea"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v9.9.2+0/OpenSSH.v9.9.2.armv7l-linux-gnueabihf.tar.gz"
[[OpenSSH]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "31ed883c36714233eef4245862a17e3c3dae008a"
libc = "musl"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "1ac4aa005b7c5497311a42d41fa3cefd543c96f0955daedc3e8bf793ebbe0942"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v9.9.2+0/OpenSSH.v9.9.2.armv7l-linux-musleabihf.tar.gz"
[[OpenSSH]]
arch = "i686"
git-tree-sha1 = "2fa860d6b8edf4bc615c5d367bc4cac385da53c3"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "85aad6b33366e7a08f5ebf547540cc2707a13395c8900ec8385b479e392d2dda"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v9.9.2+0/OpenSSH.v9.9.2.i686-linux-gnu.tar.gz"
[[OpenSSH]]
arch = "i686"
git-tree-sha1 = "a01fb11b13255b422553da05dc2df63d34251e4e"
libc = "musl"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "4e7fa88c239ae8638ed566d603b1c23e21d235d235f746541f159b85dec75843"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v9.9.2+0/OpenSSH.v9.9.2.i686-linux-musl.tar.gz"
[[OpenSSH]]
arch = "i686"
git-tree-sha1 = "0279aef37eecab0756e7b3609dd09b7e1ec253b4"
os = "windows"

    [[OpenSSH.download]]
    sha256 = "d6534f16320caef56134fe81df6794c588084cb6962c3898f044e06d571bcf9c"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v9.9.2+0/OpenSSH.v9.9.2.i686-w64-mingw32.tar.gz"
[[OpenSSH]]
arch = "powerpc64le"
git-tree-sha1 = "32fbe03b092c539b2215f37619d65b7187916047"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "867a497b11b77e0d180c17985b551f2113d192a58eea351e342956bcab532f7b"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v9.9.2+0/OpenSSH.v9.9.2.powerpc64le-linux-gnu.tar.gz"
[[OpenSSH]]
arch = "riscv64"
git-tree-sha1 = "3277e8e3ac5623f78f069c7382f9923daae2b913"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "64035c9bb2a3804186bd4d2f00ff81322659481a21f64385d0da45a41b869a3e"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v9.9.2+0/OpenSSH.v9.9.2.riscv64-linux-gnu.tar.gz"
[[OpenSSH]]
arch = "x86_64"
git-tree-sha1 = "49d2260502186bc42c60452aa59e6bb8cc28027e"
os = "macos"

    [[OpenSSH.download]]
    sha256 = "a52ffc63a88dee64c5a90a51f39357ad1645c16c45e807824464c610a5609229"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v9.9.2+0/OpenSSH.v9.9.2.x86_64-apple-darwin.tar.gz"
[[OpenSSH]]
arch = "x86_64"
git-tree-sha1 = "8da5158ff69cdbb43021d0bada6fb993355c4ed4"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "85965c2b1814f0291505e7eec57507d4a4f3f320075f9778daf43829a17b8199"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v9.9.2+0/OpenSSH.v9.9.2.x86_64-linux-gnu.tar.gz"
[[OpenSSH]]
arch = "x86_64"
git-tree-sha1 = "d3125d06060118bac31e012fae01e7fb692fbf73"
libc = "musl"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "775bf304e111db9bacb01f1a9dd093de281f94aad14c39b790c1b5c65ba72f6f"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v9.9.2+0/OpenSSH.v9.9.2.x86_64-linux-musl.tar.gz"
[[OpenSSH]]
arch = "x86_64"
git-tree-sha1 = "1e7459d63ec68abadec5b333860de318452d5345"
os = "freebsd"

    [[OpenSSH.download]]
    sha256 = "a9d7c97d2fd450a1227c1a7d3e21869b86f4c89411c03ee760a8eee082156672"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v9.9.2+0/OpenSSH.v9.9.2.x86_64-unknown-freebsd.tar.gz"
[[OpenSSH]]
arch = "x86_64"
git-tree-sha1 = "8a380ed334dece6e4696fa6c829049695e73a3b4"
os = "windows"

    [[OpenSSH.download]]
    sha256 = "8de6d3360c69955b45d8083b6c6e327e14606836600532073e7bd6af2fbe0975"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v9.9.2+0/OpenSSH.v9.9.2.x86_64-w64-mingw32.tar.gz"
