[[OpenSSH]]
arch = "aarch64"
git-tree-sha1 = "f781cdb2571ef1b4ccf5d4eb0ac84774ebb98f6e"
os = "macos"

    [[OpenSSH.download]]
    sha256 = "8d5136a8f98d03b5db2ea8b9d75d71ffd8b3006f1bf5daa6ade90db1d3b4fd30"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v9.1.0+0/OpenSSH.v9.1.0.aarch64-apple-darwin.tar.gz"
[[OpenSSH]]
arch = "aarch64"
git-tree-sha1 = "82b5b4c798c96f23f5a8a51df680c3aad746318e"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "4ea856881319354222923afa09dc446082d8a4d406c6954728557a2d46f16e0b"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v9.1.0+0/OpenSSH.v9.1.0.aarch64-linux-gnu.tar.gz"
[[OpenSSH]]
arch = "aarch64"
git-tree-sha1 = "f7270972ba07aa3edfc9274577e8dc4bcec3cd18"
libc = "musl"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "42b2eb08e9a30a6edc4c3706f2428422730affb080fa093d35f655ad5c5635f2"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v9.1.0+0/OpenSSH.v9.1.0.aarch64-linux-musl.tar.gz"
[[OpenSSH]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ce2dd72157bc47047e6b9fb2e04848145b561a1b"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "854b68615afe338c0a900260bed50a7ab052c7c91587b5a39249d580525d697a"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v9.1.0+0/OpenSSH.v9.1.0.armv6l-linux-gnueabihf.tar.gz"
[[OpenSSH]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "93108bba325cd5ab52eafddb7ac6bd01dc938764"
libc = "musl"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "c3a070087e729af6a286a6b47ce0ab8674aea7f3d394d4216bdde602897057e5"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v9.1.0+0/OpenSSH.v9.1.0.armv6l-linux-musleabihf.tar.gz"
[[OpenSSH]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "01525670bbc2ce210871a4753f1519fda7846569"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "86ffce9962ffbd6a29041cea49ad7fd1dae216210bbc5be85abc184e74bff45a"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v9.1.0+0/OpenSSH.v9.1.0.armv7l-linux-gnueabihf.tar.gz"
[[OpenSSH]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c0cf3ccc419fcd175c9f639ec0d5a3fff6a5ba4d"
libc = "musl"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "06a56eaa0c45a21d0de73a45703cc2ae72af0a050db647b53f3a953c01f03287"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v9.1.0+0/OpenSSH.v9.1.0.armv7l-linux-musleabihf.tar.gz"
[[OpenSSH]]
arch = "i686"
git-tree-sha1 = "32a7ae736caf9b219eb10d0000f2beee1e8a5f52"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "e6b12b122f46b8eadc930eb5c8e08b73184551a5d0b448ac42dee3481aedaac9"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v9.1.0+0/OpenSSH.v9.1.0.i686-linux-gnu.tar.gz"
[[OpenSSH]]
arch = "i686"
git-tree-sha1 = "6e95e0aa228b21ee852dfab8517a88ea946709d1"
libc = "musl"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "7f0c692bfc897736e6095c2e5699d433b3984eae28cb33278c96328925b0615c"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v9.1.0+0/OpenSSH.v9.1.0.i686-linux-musl.tar.gz"
[[OpenSSH]]
arch = "i686"
git-tree-sha1 = "b5215c373770cc45c73bac55b79b94e6ec25980c"
os = "windows"

    [[OpenSSH.download]]
    sha256 = "d6cb24e897a0009347e3ed098b915c8fc8562ae3a4ee278d814fe1fc1439085b"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v9.1.0+0/OpenSSH.v9.1.0.i686-w64-mingw32.tar.gz"
[[OpenSSH]]
arch = "powerpc64le"
git-tree-sha1 = "487ba33383e0b3ae376ec8c1c50c0d954e1c9f2a"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "3847713984768d554adbf30788dc3226fcdd6917ed3861e313a13d1f8ac3e1c0"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v9.1.0+0/OpenSSH.v9.1.0.powerpc64le-linux-gnu.tar.gz"
[[OpenSSH]]
arch = "x86_64"
git-tree-sha1 = "b967bd9f23d10f1ee46943eb82025e78d8762472"
os = "macos"

    [[OpenSSH.download]]
    sha256 = "a509a6bea97a4304114db5182561b490bd9a01e6a6f0a09d4b01dfd1d1a58495"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v9.1.0+0/OpenSSH.v9.1.0.x86_64-apple-darwin.tar.gz"
[[OpenSSH]]
arch = "x86_64"
git-tree-sha1 = "ef3a9c12931efd77ff8e648e8b00d29c98b40fdd"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "dda00ea9bd0bd61d011390ecb6c882a2b7c329a632512762e04200d4ade7abbf"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v9.1.0+0/OpenSSH.v9.1.0.x86_64-linux-gnu.tar.gz"
[[OpenSSH]]
arch = "x86_64"
git-tree-sha1 = "cfbb34f3af9cb7834ba0c05d63fcb671e0f72d3e"
libc = "musl"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "7dfc092b192e09a9e52412eeff031d19e6fe349ce5aae8cac27c4cec6d2b5a5e"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v9.1.0+0/OpenSSH.v9.1.0.x86_64-linux-musl.tar.gz"
[[OpenSSH]]
arch = "x86_64"
git-tree-sha1 = "dd20fbb0b3bc563d31901262528317e9b2d7269f"
os = "freebsd"

    [[OpenSSH.download]]
    sha256 = "2a974e327fceeef15820cb4be21c2efaf15782621867a5657c2320c56b1aefcb"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v9.1.0+0/OpenSSH.v9.1.0.x86_64-unknown-freebsd.tar.gz"
[[OpenSSH]]
arch = "x86_64"
git-tree-sha1 = "eca8dcb7abe5d050df7ace19c6a3391c973389f0"
os = "windows"

    [[OpenSSH.download]]
    sha256 = "5f50c323b0c7c4cbe42d4ab9f6c65f306a6e53f1a424d55acd2cf9e7f2f3975d"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v9.1.0+0/OpenSSH.v9.1.0.x86_64-w64-mingw32.tar.gz"
