[[OpenSSH]]
arch = "aarch64"
git-tree-sha1 = "3fa3ae5a55c864014d9c801405cb178ff567c9ea"
os = "macos"

    [[OpenSSH.download]]
    sha256 = "26a5bbec9f28fcf2d4a9a01c46eab90a84c8ecc946fa00f6992ce9819ad03b35"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.2.1+0/OpenSSH.v10.2.1.aarch64-apple-darwin.tar.gz"
[[OpenSSH]]
arch = "aarch64"
git-tree-sha1 = "ebf2a36d0c52c685ca0acb5f0d9e9f22270b1a83"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "1d6417530356a86f4333d4a309f361a4ce5a89ec86403275cc16b36437cb9db2"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.2.1+0/OpenSSH.v10.2.1.aarch64-linux-gnu.tar.gz"
[[OpenSSH]]
arch = "aarch64"
git-tree-sha1 = "fe27a84cc3373c9ef4dec5bf7f594c9c57f429a5"
libc = "musl"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "fcb6d3dd28632ebc945b57639617a9947f7be2c20ddb939db8363619ba4c5237"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.2.1+0/OpenSSH.v10.2.1.aarch64-linux-musl.tar.gz"
[[OpenSSH]]
arch = "aarch64"
git-tree-sha1 = "797b3d132549cfa2cc5fff0e2b3ae1de7d569323"
os = "freebsd"

    [[OpenSSH.download]]
    sha256 = "90b7d19a70e85391e3624c325ee6d2169093dc1de5282804669f51e57ba12146"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.2.1+0/OpenSSH.v10.2.1.aarch64-unknown-freebsd.tar.gz"
[[OpenSSH]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ab17cdbc6e53f58a2f0f2e3292f80184d3e89ffa"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "23ca235ec2e1e2cf2b701c5ed6a28048dbbb38c399009e032d2d78f481f7e44f"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.2.1+0/OpenSSH.v10.2.1.armv6l-linux-gnueabihf.tar.gz"
[[OpenSSH]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1ee6964f98be8983ea978ed8306c1a92b1136196"
libc = "musl"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "293cc066bec09c754dff1c9722ebff997c0570364a71672ca92b04bc92a6bc79"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.2.1+0/OpenSSH.v10.2.1.armv6l-linux-musleabihf.tar.gz"
[[OpenSSH]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "05e5d5bcede4f308eca3bb850848c5cbf5806eaf"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "e3552815d07c2ffa0b519b169492afb52a58b727cdc1408551e7ae5bfc2cdf12"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.2.1+0/OpenSSH.v10.2.1.armv7l-linux-gnueabihf.tar.gz"
[[OpenSSH]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7bc1a1da2bb28b8daac1bc69f652ff898fb62492"
libc = "musl"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "bcfb37c7f7b9d149a51bf930a0ae259a69d8ba93861f71d74db659f2f9a88d80"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.2.1+0/OpenSSH.v10.2.1.armv7l-linux-musleabihf.tar.gz"
[[OpenSSH]]
arch = "i686"
git-tree-sha1 = "29a68b2636f1fa1af9b832688942ada900b8926d"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "a5c326a7fb7257745d10dbfe06eb90f100df9292c3004300a4fb0f5a46703270"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.2.1+0/OpenSSH.v10.2.1.i686-linux-gnu.tar.gz"
[[OpenSSH]]
arch = "i686"
git-tree-sha1 = "abd137bd397b83887782984b79c0debd29e5b3cd"
libc = "musl"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "410dfe115d8aa180b64e8825eae0b2f362ac881864ed196dfc2a6ae94d1d4e76"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.2.1+0/OpenSSH.v10.2.1.i686-linux-musl.tar.gz"
[[OpenSSH]]
arch = "i686"
git-tree-sha1 = "0279aef37eecab0756e7b3609dd09b7e1ec253b4"
os = "windows"

    [[OpenSSH.download]]
    sha256 = "d6534f16320caef56134fe81df6794c588084cb6962c3898f044e06d571bcf9c"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.2.1+0/OpenSSH.v10.2.1.i686-w64-mingw32.tar.gz"
[[OpenSSH]]
arch = "powerpc64le"
git-tree-sha1 = "07a940cad8502ea209c813c0d3228716a11a46bd"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "cf2fc6a43f7d0157e3f43622df44e0015931c1d3e7bb7aee9a5491e3b1f267d1"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.2.1+0/OpenSSH.v10.2.1.powerpc64le-linux-gnu.tar.gz"
[[OpenSSH]]
arch = "riscv64"
git-tree-sha1 = "36d3b0fcdfc56cabf41ec91f312e25de12d9c04a"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "8e263cda2593656e7c6ea314598dc80cc8740c5a1f992729686dda0fbff6d449"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.2.1+0/OpenSSH.v10.2.1.riscv64-linux-gnu.tar.gz"
[[OpenSSH]]
arch = "x86_64"
git-tree-sha1 = "25a416a6fe8e901c027a137d33acab121ff3f399"
os = "macos"

    [[OpenSSH.download]]
    sha256 = "07e77c8f6170fe56c3e9d600bced28a03aae95787e898f3833587c7f434982f3"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.2.1+0/OpenSSH.v10.2.1.x86_64-apple-darwin.tar.gz"
[[OpenSSH]]
arch = "x86_64"
git-tree-sha1 = "fc7cfafb3218745ad80066127ae3decb2c8a31f6"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "22d0174730582e4bfd174eae6e7e20c0ed1ba105b6a5df736835296348ad4081"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.2.1+0/OpenSSH.v10.2.1.x86_64-linux-gnu.tar.gz"
[[OpenSSH]]
arch = "x86_64"
git-tree-sha1 = "fed46f59e78cef234d5d4e6c9cf589387f5d86d0"
libc = "musl"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "65bbc6ba3df91de2fbb450c945feeb3599bcefa75544bb8ace20f3dda1ccc115"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.2.1+0/OpenSSH.v10.2.1.x86_64-linux-musl.tar.gz"
[[OpenSSH]]
arch = "x86_64"
git-tree-sha1 = "cfb7ec456171cf5f00e7f3b42e60a563c55897f9"
os = "freebsd"

    [[OpenSSH.download]]
    sha256 = "d22b0b8e4ffc0d56a4afc62632c92d6ddef324969f2cc278f661b2e830917bfe"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.2.1+0/OpenSSH.v10.2.1.x86_64-unknown-freebsd.tar.gz"
[[OpenSSH]]
arch = "x86_64"
git-tree-sha1 = "8a380ed334dece6e4696fa6c829049695e73a3b4"
os = "windows"

    [[OpenSSH.download]]
    sha256 = "8de6d3360c69955b45d8083b6c6e327e14606836600532073e7bd6af2fbe0975"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.2.1+0/OpenSSH.v10.2.1.x86_64-w64-mingw32.tar.gz"
