[[OpenSSH]]
arch = "aarch64"
git-tree-sha1 = "0909e6a63e05a213473a98a598c3dba773777522"
os = "macos"

    [[OpenSSH.download]]
    sha256 = "ce6666dc8b41398da7c11d7d104a4d7072f8f9b4620e303cc807668fd67b9dab"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v8.9.0+0/OpenSSH.v8.9.0.aarch64-apple-darwin.tar.gz"
[[OpenSSH]]
arch = "aarch64"
git-tree-sha1 = "47ccb6cafebeb1b13f0d1f696c070eab23676e75"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "d1a2ba5d54f9ba862a34abf733c4d53ad1c81bf6777f259e9b4955a1fded66cc"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v8.9.0+0/OpenSSH.v8.9.0.aarch64-linux-gnu.tar.gz"
[[OpenSSH]]
arch = "aarch64"
git-tree-sha1 = "8c590a52f1432478a9d4bcca10491c1e2cef8fe4"
libc = "musl"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "4fd208b03ba31c76d9963cfba356b6976d0c8fb6d61435ba95a7bf3e48bfe0db"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v8.9.0+0/OpenSSH.v8.9.0.aarch64-linux-musl.tar.gz"
[[OpenSSH]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "96814ae086b28d716bf88a5ec9181feba8ff031c"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "57189303ce1df722723ce6594415512e592dd960d6a4f614efb22e31e89aeb3e"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v8.9.0+0/OpenSSH.v8.9.0.armv6l-linux-gnueabihf.tar.gz"
[[OpenSSH]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "81c1a1d932ecc0e2700f199f03d702934fbb937e"
libc = "musl"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "ff6305160ff8a820703da5af47c237c84431d9a65d1a23c9f2f372c9386d2b8b"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v8.9.0+0/OpenSSH.v8.9.0.armv6l-linux-musleabihf.tar.gz"
[[OpenSSH]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2017811d25cf2804d58f6b9b1d993dc37e7f53d5"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "23ee05136959e68d4864dddbe3e34ebac1702f3851f39316292405d6199164e2"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v8.9.0+0/OpenSSH.v8.9.0.armv7l-linux-gnueabihf.tar.gz"
[[OpenSSH]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c8b5415e9a7d2a9c7a5c0cc0b54d18c44135cd3a"
libc = "musl"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "81542f53a39a867227dd77ad967f333ca864ee639cc71841c51c97bab79b9018"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v8.9.0+0/OpenSSH.v8.9.0.armv7l-linux-musleabihf.tar.gz"
[[OpenSSH]]
arch = "i686"
git-tree-sha1 = "3418ceda46fb6dadbfc58426adc03783945bb8c9"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "246ead6ea5c24c3d4038e44b6483859c304564894780f6bb11c285036b41dbda"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v8.9.0+0/OpenSSH.v8.9.0.i686-linux-gnu.tar.gz"
[[OpenSSH]]
arch = "i686"
git-tree-sha1 = "72c94ae6c7fcad7341cf2c89fc41c30c252592ea"
libc = "musl"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "02d5539c1e8f7cf3eff8b69d0d2c329aae3bfb9d36c43685833af8ef1c2230b9"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v8.9.0+0/OpenSSH.v8.9.0.i686-linux-musl.tar.gz"
[[OpenSSH]]
arch = "i686"
git-tree-sha1 = "33e289a9951e1c81ccb7de08fc03c22c78f49cb7"
os = "windows"

    [[OpenSSH.download]]
    sha256 = "e2266d40be015309afd788e1043a42a28b5aed3cbaa7c473fd4d6d9536653077"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v8.9.0+0/OpenSSH.v8.9.0.i686-w64-mingw32.tar.gz"
[[OpenSSH]]
arch = "powerpc64le"
git-tree-sha1 = "3ecb47888987bb7131ae0e6474c133f660fe5ebe"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "7435bab0d5d380db9ed4ce90113bfbe7272ae58f5d10bc51be17b8e97121b575"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v8.9.0+0/OpenSSH.v8.9.0.powerpc64le-linux-gnu.tar.gz"
[[OpenSSH]]
arch = "x86_64"
git-tree-sha1 = "dbb86cc980d5b7912e64930c6464b6f073611d26"
os = "macos"

    [[OpenSSH.download]]
    sha256 = "0c5b7f28e686a52f2f0b4deda2360ea302494e3fec8009dbb6f378885fd1d30f"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v8.9.0+0/OpenSSH.v8.9.0.x86_64-apple-darwin.tar.gz"
[[OpenSSH]]
arch = "x86_64"
git-tree-sha1 = "8a0148f779c107def91abf0c04a27ecee5c8baa2"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "9adb94a38500f3c69a5b5afedb24b4ca833586c4abf296b7b3ae5a03d156256e"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v8.9.0+0/OpenSSH.v8.9.0.x86_64-linux-gnu.tar.gz"
[[OpenSSH]]
arch = "x86_64"
git-tree-sha1 = "b28d570167317625f1f4b23ecafb2e13ca4ab6d3"
libc = "musl"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "25db10357da625d928fd6015028c0fc860e3493ef223f970b59255977b1387a0"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v8.9.0+0/OpenSSH.v8.9.0.x86_64-linux-musl.tar.gz"
[[OpenSSH]]
arch = "x86_64"
git-tree-sha1 = "9e9c9b65db695a24096e6b17721dc304cd846fff"
os = "freebsd"

    [[OpenSSH.download]]
    sha256 = "f63c07bc3cae9e2858f4b373ae4955a2af3ea6df06c930add22759736002eea7"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v8.9.0+0/OpenSSH.v8.9.0.x86_64-unknown-freebsd.tar.gz"
[[OpenSSH]]
arch = "x86_64"
git-tree-sha1 = "f24c497037d72bc93e29b859f5574554a1a77307"
os = "windows"

    [[OpenSSH.download]]
    sha256 = "291bd973373557c5c4576313599a1750c44f7a11a96f08835a77516df41b4b76"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v8.9.0+0/OpenSSH.v8.9.0.x86_64-w64-mingw32.tar.gz"
