[[OpenSSH]]
arch = "aarch64"
git-tree-sha1 = "42aca1c3df8561e7adcf3018b7fa3ff404de012f"
os = "macos"

    [[OpenSSH.download]]
    sha256 = "fdfff3a663cc16ff65992f256b2202c1d4e6c380be6cab5b982d7a53e6910cd7"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.0.2+0/OpenSSH.v10.0.2.aarch64-apple-darwin.tar.gz"
[[OpenSSH]]
arch = "aarch64"
git-tree-sha1 = "20dc3f19b30e3342d2c3d358f97ad517a0a0276e"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "d0cc8359a066180f92dd24bb556863bb258903d9a4a10b2d34243827c9766c66"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.0.2+0/OpenSSH.v10.0.2.aarch64-linux-gnu.tar.gz"
[[OpenSSH]]
arch = "aarch64"
git-tree-sha1 = "9317dca3342602e6174263f6f341854ae10ea170"
libc = "musl"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "3d048cde522b77dd0d8ed8c4ce9a3ff3c1e3df5b1c748882266f9114f18bf5d6"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.0.2+0/OpenSSH.v10.0.2.aarch64-linux-musl.tar.gz"
[[OpenSSH]]
arch = "aarch64"
git-tree-sha1 = "91b3e498fcd27b8028b7edb9dcdbd96f75ca26c0"
os = "freebsd"

    [[OpenSSH.download]]
    sha256 = "4ebfecdeea5b2b6bdf68af0b661e2b3a9043d1d5f740dc234637a0f8cab63670"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.0.2+0/OpenSSH.v10.0.2.aarch64-unknown-freebsd.tar.gz"
[[OpenSSH]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2d5a7984be837bf26fe52b4149e2d0dc383e3f52"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "e553b4e097fe1ae0d79e1fe140730accd77e21bd72389897a5793e5242cc1813"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.0.2+0/OpenSSH.v10.0.2.armv6l-linux-gnueabihf.tar.gz"
[[OpenSSH]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8e22123a474e008fd236a958401730f6ae36e41e"
libc = "musl"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "ccab89d4816a6110e73e241822af066f1404019d4cec39eb6fee7ed184964361"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.0.2+0/OpenSSH.v10.0.2.armv6l-linux-musleabihf.tar.gz"
[[OpenSSH]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9004dad8f00a66b2303bf0a894b78adcd0475a60"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "8f7e7988523e16afa9cdfe368b15d7b9861d071e6c7be385b29cd3374fb706b7"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.0.2+0/OpenSSH.v10.0.2.armv7l-linux-gnueabihf.tar.gz"
[[OpenSSH]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e7db92971042d6262be4f494e79f10e2cae6c05a"
libc = "musl"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "8b23d3323cff85c434de91b83f850b51f6637ef5404f3d98733a27cf4be6b38a"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.0.2+0/OpenSSH.v10.0.2.armv7l-linux-musleabihf.tar.gz"
[[OpenSSH]]
arch = "i686"
git-tree-sha1 = "84fd6ddb02cafefbabb230daf515dffd71d56fad"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "d99ca664fd29788e14b7dbc318ef2becd1c57362fbc620e9bb15f778c0a27fa7"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.0.2+0/OpenSSH.v10.0.2.i686-linux-gnu.tar.gz"
[[OpenSSH]]
arch = "i686"
git-tree-sha1 = "547679d4a6b229c8b6670ddd3e224f07d6f882da"
libc = "musl"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "b9cdaf3c6a393aa52d8bf351094127807ee3ccb594820a6273c17fdd37d896f8"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.0.2+0/OpenSSH.v10.0.2.i686-linux-musl.tar.gz"
[[OpenSSH]]
arch = "i686"
git-tree-sha1 = "0279aef37eecab0756e7b3609dd09b7e1ec253b4"
os = "windows"

    [[OpenSSH.download]]
    sha256 = "d6534f16320caef56134fe81df6794c588084cb6962c3898f044e06d571bcf9c"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.0.2+0/OpenSSH.v10.0.2.i686-w64-mingw32.tar.gz"
[[OpenSSH]]
arch = "powerpc64le"
git-tree-sha1 = "fd33fdfe7ef87eee53ae1941e31f9dcc387869b7"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "5a1ab6a3db662390d6534c2ed378f3f8fd2ce07f5e9c21e66bf460d4af3febca"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.0.2+0/OpenSSH.v10.0.2.powerpc64le-linux-gnu.tar.gz"
[[OpenSSH]]
arch = "riscv64"
git-tree-sha1 = "31480663dc167c6f8e2f3752a1e6f9244fa16c18"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "76c7eb7657a06d32801e45153301e9474bd29cea042feb079593a6009e2c59ad"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.0.2+0/OpenSSH.v10.0.2.riscv64-linux-gnu.tar.gz"
[[OpenSSH]]
arch = "x86_64"
git-tree-sha1 = "f74dd32cef69e0c80198895f82671e76edd7e512"
os = "macos"

    [[OpenSSH.download]]
    sha256 = "8422fe3cb799bf820de3744e8b7108be95b16453c4be8fa346ae0aadd429ec6d"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.0.2+0/OpenSSH.v10.0.2.x86_64-apple-darwin.tar.gz"
[[OpenSSH]]
arch = "x86_64"
git-tree-sha1 = "42f858d37092b1cd8328aaa7f38acb71dac43a2c"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "023d079e899f8205e393d1f5dc2aa6dd8f6f8489d4a45b6342f1a679a63bfaff"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.0.2+0/OpenSSH.v10.0.2.x86_64-linux-gnu.tar.gz"
[[OpenSSH]]
arch = "x86_64"
git-tree-sha1 = "3b0a90a9bb901982c4495ecd5f99a5f2a336e630"
libc = "musl"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "af5fdec1252af5892e51c7cba2f1789c2c945df6e75470cd76e7ed9306b8099a"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.0.2+0/OpenSSH.v10.0.2.x86_64-linux-musl.tar.gz"
[[OpenSSH]]
arch = "x86_64"
git-tree-sha1 = "b61c46fc25dd7634fc3ee98549ec055969369100"
os = "freebsd"

    [[OpenSSH.download]]
    sha256 = "dab2c6162d3ecee399774cbb821db512dc946c55c555742c48da4245857e73d6"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.0.2+0/OpenSSH.v10.0.2.x86_64-unknown-freebsd.tar.gz"
[[OpenSSH]]
arch = "x86_64"
git-tree-sha1 = "8a380ed334dece6e4696fa6c829049695e73a3b4"
os = "windows"

    [[OpenSSH.download]]
    sha256 = "8de6d3360c69955b45d8083b6c6e327e14606836600532073e7bd6af2fbe0975"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.0.2+0/OpenSSH.v10.0.2.x86_64-w64-mingw32.tar.gz"
