[[OpenSSH]]
arch = "aarch64"
git-tree-sha1 = "bf80993b0e91a103893310008e7dcffb3781ad6f"
os = "macos"

    [[OpenSSH.download]]
    sha256 = "fb5b2fd76a9ab285686e0c929128631b16be09fa764a0883e59258208f449b0c"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.3.1+0/OpenSSH.v10.3.1.aarch64-apple-darwin.tar.gz"
[[OpenSSH]]
arch = "aarch64"
git-tree-sha1 = "1945c0dee92e2af7c696ee381cb0e37c9418203f"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "f3241768f461934db282adcf389e32768840f0ef211c9c0437f24f22fd72e9c8"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.3.1+0/OpenSSH.v10.3.1.aarch64-linux-gnu.tar.gz"
[[OpenSSH]]
arch = "aarch64"
git-tree-sha1 = "bd1af14f6a58be46b176119715012a5bfb95c53d"
libc = "musl"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "39844e5fdef1c228baf91ad8c4d1a45aca87874e8b0a5f9ac7bcac51cc36ebae"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.3.1+0/OpenSSH.v10.3.1.aarch64-linux-musl.tar.gz"
[[OpenSSH]]
arch = "aarch64"
git-tree-sha1 = "87d8b4eb6a7de70b96096d617ce5e1752f620697"
os = "freebsd"

    [[OpenSSH.download]]
    sha256 = "8f0c07514f5f2723d92f81707a4b84330a5a9195c8aee2e880f16b2ac1ce290a"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.3.1+0/OpenSSH.v10.3.1.aarch64-unknown-freebsd.tar.gz"
[[OpenSSH]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d700bd3cbfa12d01bb44c5f7ed3b6e24f0653d82"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "b0ebd32dd842618926b2b610f4022a71c6a448fbed080c627aac00ce3d051d11"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.3.1+0/OpenSSH.v10.3.1.armv6l-linux-gnueabihf.tar.gz"
[[OpenSSH]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "15668bc45eca04d5aea571985fe993c5bdefa230"
libc = "musl"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "38d8d9a87750d231cd7648fc15089adb1c922a1f26272e4d92e402b6d6826ea9"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.3.1+0/OpenSSH.v10.3.1.armv6l-linux-musleabihf.tar.gz"
[[OpenSSH]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6316739dd4e7f83f6c702b047caf3e5d5167d5f2"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "ac3ad3e8a61e061c9e49a8e6d880284e631d6df60ec6d018f2a880d559c86779"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.3.1+0/OpenSSH.v10.3.1.armv7l-linux-gnueabihf.tar.gz"
[[OpenSSH]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b934a480635dc96cb35653561c71eeb0274a9246"
libc = "musl"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "d4b411b0c7ef522e0b2eaa43f162af15282a84ff88c88a9ad2fe1396ff2c0049"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.3.1+0/OpenSSH.v10.3.1.armv7l-linux-musleabihf.tar.gz"
[[OpenSSH]]
arch = "i686"
git-tree-sha1 = "b282b8e2067ee417ef1e7127776409482ecfea67"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "2f9958842acbe254642b03cd52fc319c070985e0ca7ff964e3ff0b1b1f96309e"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.3.1+0/OpenSSH.v10.3.1.i686-linux-gnu.tar.gz"
[[OpenSSH]]
arch = "i686"
git-tree-sha1 = "e9821ff45b6aa0dc14c472013ebb15b47b506ea2"
libc = "musl"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "e0ccddbb523538bc9872e72f6a265cb1c7e41f6ce79a5c79b3039e8f52ce5105"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.3.1+0/OpenSSH.v10.3.1.i686-linux-musl.tar.gz"
[[OpenSSH]]
arch = "i686"
git-tree-sha1 = "ec95677979b1093ccdfb4d177a0a8e751cc915f3"
os = "windows"

    [[OpenSSH.download]]
    sha256 = "f776eb0707b2d5e349b2f9a1d4db4932111a9eeefed2c98d263a4c36482aaf94"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.3.1+0/OpenSSH.v10.3.1.i686-w64-mingw32.tar.gz"
[[OpenSSH]]
arch = "powerpc64le"
git-tree-sha1 = "e3b5d5e36d3e5f15f09920a75768ff2d090fd0f3"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "d9abd97452c16a1b08d16ec96bcc3e809f0b3022babe2a8560a80d2606c6ee68"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.3.1+0/OpenSSH.v10.3.1.powerpc64le-linux-gnu.tar.gz"
[[OpenSSH]]
arch = "riscv64"
git-tree-sha1 = "e7ad7750512ccdc986fa804067bb528262d18cbf"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "959f6f324ee62e1d33dd1a1465218fb001041f3cd20215132e559b82d59196cc"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.3.1+0/OpenSSH.v10.3.1.riscv64-linux-gnu.tar.gz"
[[OpenSSH]]
arch = "x86_64"
git-tree-sha1 = "a9919de28d7052b5d49f3dadafea98f7c4c09662"
os = "macos"

    [[OpenSSH.download]]
    sha256 = "a7442c13dbbd0e90326dd398b56b79b74e000699df04fd699022b07cbda8a7fc"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.3.1+0/OpenSSH.v10.3.1.x86_64-apple-darwin.tar.gz"
[[OpenSSH]]
arch = "x86_64"
git-tree-sha1 = "0b9f3ad369a4ec650408069c7d6794c14a3c815c"
libc = "glibc"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "62f9bbb400fd04e13d7beae2e9ce5a7f2bb222d49d8314f89cd3e86db606327e"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.3.1+0/OpenSSH.v10.3.1.x86_64-linux-gnu.tar.gz"
[[OpenSSH]]
arch = "x86_64"
git-tree-sha1 = "9d1cdaf2017048015561de68530acf97e043f85b"
libc = "musl"
os = "linux"

    [[OpenSSH.download]]
    sha256 = "38fe76dadbd65cd7f6ebf2ebcd9be9aef3ba2caad1ce06a1bd9735be65621d7e"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.3.1+0/OpenSSH.v10.3.1.x86_64-linux-musl.tar.gz"
[[OpenSSH]]
arch = "x86_64"
git-tree-sha1 = "0ceb9232a4c70c7cda091e7811f487f1f6d7b870"
os = "freebsd"

    [[OpenSSH.download]]
    sha256 = "964aeb09f54fd16b78d9feb121411491910cec7a11f8346cdd583f7508a9784e"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.3.1+0/OpenSSH.v10.3.1.x86_64-unknown-freebsd.tar.gz"
[[OpenSSH]]
arch = "x86_64"
git-tree-sha1 = "d157524e6bef4b01e05834a054929a37016b6ac8"
os = "windows"

    [[OpenSSH.download]]
    sha256 = "a0c0a69b464becdffebc40455f05e8be3747e5ea0a56a77640238c2a2a2d2074"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/releases/download/OpenSSH-v10.3.1+0/OpenSSH.v10.3.1.x86_64-w64-mingw32.tar.gz"
